#
# Configuración de la base de dato.
#
# La base de datos a utilizad es Postgres.
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default
  database: <%= ENV.fetch("DATABASE") %>
  username: <%= ENV.fetch("USERNAME") %>
  password: <%= ENV.fetch("PASSWORD") %>
production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_URL") %>